language: bash

os:
  - linux
  - osx

sudo: required

branches:
  only:
    - master

notifications:
  email: false

env:
  - ARCHDEFS_VERSION=2.0.3
  - ARCHDEFS_VERSION=master

before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get update -qq; sudo apt-get install -qq wget gfortran; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update; fi
  - mkdir -p $HOME/archdefs
  - cd $HOME/archdefs
  - if [[ $ARCHDEFS_VERSION == "master" ]]; then
      git clone https://github.com/ralna/ARCHDefs.git;
      export ARCHDEFS=$HOME/archdefs/ARCHDefs;
    else
      wget https://github.com/ralna/ARCHDefs/archive/v$ARCHDEFS_VERSION.tar.gz;
      export ARCHDEFS=$HOME/archdefs/ARCHDefs-$ARCHDEFS_VERSION;
      tar xvf v$ARCHDEFS_VERSION.tar.gz;
    fi
  - export SIFDECODE=$TRAVIS_BUILD_DIR
  - export MASTSIF=$SIFDECODE/sif
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

install:
  - cd $TRAVIS_BUILD_DIR
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then printf "6\n2\n5\n" > sifdecode.input; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then printf "13\n2\n" > sifdecode.input; fi
  - printf "nny" >> sifdecode.input
  - ./install_sifdecode < sifdecode.input
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export MYARCH=pc64.lnx.gfo; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then export MYARCH=mac64.osx.gfo; fi

script:
  - ./bin/sifdecoder ROSENBR.SIF
  - grep DOUBLE ELFUN.f || false
  - ./bin/sifdecoder -sp ROSENBR.SIF
  - grep REAL ELFUN.f || false
